version: '3'
services:
  app:
    container_name: my-node-mongo-docker
    restart: always
    build: .
    ports:
      - '3500:3500'
    links:
      - mongo
    environment:
     - mongo_url=mongodb://mongo:27017/api
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
